# Generated by Django 5.1 on 2024-09-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_category_slug_alter_subcategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='off_price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Off Price'),
        ),
    ]
