# Generated by Django 5.1 on 2024-09-05 12:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_off_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='offer',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Offer'),
        ),
    ]
