# Generated by Django 5.1 on 2024-09-12 11:47

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_product_off_price_alter_product_sell_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=autoslug.fields.AutoSlugField(allow_unicode=True, editable=False, populate_from='title', unique=True, verbose_name='Slug'),
        ),
    ]
